stages:
  - build
  - push
  - deploy

build_image:
  stage: build
  script:
    - docker build -t erddap-content .

push_image:
  stage: push
  only:
    - master
  script:
    - docker tag erddap-content registry.axiom/erddap-content:latest
    - docker push registry.axiom/erddap-content:latest

push_image_branch:
  stage: push
  only:
    - branches
  except:
    - master
  script:
    - docker tag erddap-content registry.axiom/erddap-content:$CI_BUILD_REF_NAME
    - docker push registry.axiom/erddap-content:$CI_BUILD_REF_NAME

deploy_prod:
  stage: deploy
  environment: production
  only:
    - tags
  script:
    - docker run --rm registry.axiom/ansible ap apps-prod erddap-docker-regions --tags deploy --skip-tags restart_container
