#!/bin/bash
REGION=$1
OUTPUT_FOLDER="/output/$REGION"
mkdir -p "$OUTPUT_FOLDER"

# Run any generate_* files that are executable
for g in $(find "./regions/$REGION" -name "generate_*" -type f); do
    bash $g
done

# Merge all of the individual dataset XML files in a single datasets.xml
FOLDER=$(dirname "./regions/$REGION/datasets")
TMP="$FOLDER/datasets.tmp"
MASTER="$OUTPUT_FOLDER/datasets.xml"
PROCESSED="$FOLDER/datasets.processed"
if [ -e $TMP ]; then
    rm -f $TMP  # Clear file
fi
for x in $(find $FOLDER -regextype posix-extended -regex '.*[0-9]{4}_.*\.xml' -type f | sort); do
    cat $x >> $TMP  # Append contents
done

if [ -e $TMP ]; then
    if [ -e $PROCESSED ]; then
        rm -f $PROCESSED  # Clear file
    fi
    python process_dataset_changes.py $MASTER $TMP $PROCESSED
    rm $TMP
fi

if [ -e $PROCESSED ]; then
    xmllint --format $PROCESSED --noblanks --output $MASTER
    rm $PROCESSED
fi

# Copy other content to an output directory
echo "Copying data to $OUTPUT_FOLDER"
cp "$FOLDER/setup.xml" "$OUTPUT_FOLDER/setup.xml"
cp -r "$FOLDER/images" "$OUTPUT_FOLDER"
