#!/bin/bash

# Generate regional stations
python oikos_stations.py \
    -r cencoos \
    -o cencoos/datasets/0050_regional_stations.xml \
    -p CeNCOOS \
    -e jpatterson@mbari.org \
    -i CeNCOOS \
    -l 20679 20542 20063 20523 20363 20362 20358 20366 20357 20364 48035 20365 \
    -t "(CeNCOOS)"

python oikos_stations.py \
    -r secoora \
    -o secoora/datasets/0050_regional_stations.xml \
    -p SECOORA \
    -e vembu@secoora.org \
    -i SECOORA \
    -l 60375 60377 60378 60379 60380 60381 60382 60383 60384 60386 60387 60388 \
60395 60396 60397 60398 60399 60400 60401 60403 60405 60406 60407 60408 60410 \
60411 60415 60416 60417 60418 60419 60420 60421 60423 60424 \
    -t "(SECOORA)"

python oikos_stations.py \
    -r aoos \
    -o aoos/datasets/0050_regional_stations.xml \
    -p AOOS \
    -i AOOS \
    -t "(AOOS)"

python oikos_stations.py \
    -r all \
    -o all/datasets/0050_regional_stations.xml \
    -p Axiom \
    -i Axiom

python oikos_stations.py \
    -r all \
    -o usgs-cmg/datasets/0050_regional_stations.xml \
    -p "USGS Coastal and Marine Geology Program" \
    -e rsignell@usgs.gov \
    -i "USGS Coastal and Marine Geology Program" \
    -d 86

# This merges all of the individual dataset XML files in a single datasets.xml
# file to be used in ERDDAP.
for x in $(find . -name "datasets" -type d); do

    FOLDER=$(dirname $x)
    TMP=$FOLDER/datasets.tmp
    MASTER=$FOLDER/datasets.xml

    if [ -e $TMP ]; then
        rm -f $TMP  # Clear file
    fi
    for x in $(find $FOLDER -regextype posix-extended -regex '.*[0-9]{4}_.*\.xml' -type f | sort); do
        cat $x >> $TMP  # Append contents
    done

    if [ -e $TMP ]; then
        xmllint --format $TMP --noblanks --output $MASTER
        rm $TMP
    fi
done
