#!/bin/sh
#
# This merges all of the individual dataset XML files in a single datasets.xml
# file to be used in ERDDAP.

bash generate_stations

for x in $(find . -name "datasets" -type d); do
    FOLDER=$(dirname $x)
    TMP=$FOLDER/datasets.tmp
    MASTER=$FOLDER/datasets.xml

    if [ -e $TMP ]; then
        rm -f $TMP  # Clear file
    fi
    for x in $(find $FOLDER -regextype posix-extended -regex '.*[0-9]{4}_.*\.xml' -type f | sort); do
        cat $x >> $TMP  # Append contents
    done

    if [ -e $TMP ]; then
        xmllint --format $TMP --noblanks --output $MASTER
        rm $TMP
    fi

    git add $MASTER

done
