#!/bin/bash
# RELDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# python oikos_stations.py \
#     --link \
#     --region "global" \
#     --output "$RELDIR/datasets/0050_regional_stations.xml"
