#!/bin/bash
RELDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# SECOORA Gliders
python gliders.py \
    ioos \
    -o "$RELDIR/datasets/0070_gliders.xml" \
    -n bass-20160909T1733 modena-20160909T1758 ramses-20160909T2028 \
salacia-20160919T2028 \
    -t "(SECOORA) Glider"
